services:
  frontend:
    env_file:
      - ./.env
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./candle
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py migrate &&
            python manage.py seed &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:9.5.0
    container_name: mysql-container
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: candle
    ports:
      - "3000:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data: