# Generated by Django 6.0 on 2025-12-28 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_type_cat_associations_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_cat_associations',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category'),
        ),
    ]
