# Generated by Django 6.0 on 2025-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_type_cat_associations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
