# Generated by Django 6.0 on 2025-12-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_entry_questionentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionentry',
            name='score',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Slightly Disagree'), (4, 'Slightly Agree'), (5, 'Agree'), (6, 'Strongly Agree')]),
        ),
    ]
