# Generated by Django 6.0 on 2025-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_questionentry_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cynicism_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exhaustion_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reduced_accomplishment_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='total_score',
            field=models.FloatField(null=True),
        ),
    ]
