# Generated by Django 6.0 on 2025-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_entry_cynicism_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionentry',
            name='score',
            field=models.IntegerField(choices=[(0, 'Strongly Disagree'), (1, 'Disagree'), (2, 'Slightly Disagree'), (3, 'Slightly Agree'), (4, 'Agree'), (5, 'Strongly Agree')]),
        ),
    ]
