# Generated by Django 6.0 on 2026-01-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_questionentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionentry',
            name='user',
        ),
    ]
